export type VibeKey = "nuclear" | "cursed" | "cope" | "yikes" | "dead" | "rip";

export interface Layoff {
  id: number;
  company: string;
  ticker: string;
  emoji: string;
  accentColor: string;
  count: number;
  pct: number;
  date: string; // ISO
  vibe: VibeKey;
  vibeLabel: string;
  note: string;
}

export const VIBES: Record<VibeKey, { label: string; emoji: string; tw: string }> = {
  nuclear: { label: "NUCLEAR",  emoji: "☢️",  tw: "bg-red-500/10 border-red-500/40 text-red-400" },
  cursed:  { label: "CURSED",   emoji: "🧿",  tw: "bg-purple-500/10 border-purple-500/40 text-purple-400" },
  cope:    { label: "COPE",     emoji: "💪",  tw: "bg-orange-500/10 border-orange-500/40 text-orange-400" },
  yikes:   { label: "YIKES",   emoji: "😬",  tw: "bg-yellow-500/10 border-yellow-500/40 text-yellow-400" },
  dead:    { label: "DEAD",     emoji: "🚽",  tw: "bg-red-400/10 border-red-400/40 text-red-300" },
  rip:     { label: "RIP",      emoji: "🪦",  tw: "bg-slate-500/10 border-slate-500/40 text-slate-400" },
};

export const layoffs: Layoff[] = [
  {
    id: 1,
    company: "Amazon",
    ticker: "AMZN",
    emoji: "📦",
    accentColor: "#ff9900",
    count: 27000,
    pct: 9,
    date: "2023-01-04",
    vibe: "nuclear",
    vibeLabel: "☢️ NUCLEAR",
    note: "Biggest layoff in Amazon history. Next-day delivery of pink slips. Prime member benefits do NOT include job security.",
  },
  {
    id: 2,
    company: "Meta",
    ticker: "META",
    emoji: "📱",
    accentColor: "#1877f2",
    count: 21000,
    pct: 25,
    date: "2023-03-14",
    vibe: "nuclear",
    vibeLabel: "☢️ NUCLEAR",
    note: "Zuck called it the \"Year of Efficiency\". One in four employees discovered they were inefficient.",
  },
  {
    id: 3,
    company: "Intel",
    ticker: "INTC",
    emoji: "🧮",
    accentColor: "#0071c5",
    count: 15000,
    pct: 15,
    date: "2024-08-01",
    vibe: "dead",
    vibeLabel: "🚽 DEAD",
    note: "The chips are down. Literally. Stock down 60% that year and they took it out on the employees.",
  },
  {
    id: 4,
    company: "Tesla",
    ticker: "TSLA",
    emoji: "⚡",
    accentColor: "#e82127",
    count: 14000,
    pct: 10,
    date: "2024-04-15",
    vibe: "nuclear",
    vibeLabel: "☢️ NUCLEAR",
    note: "Entire Supercharger team: gone. Emails sent at 3am. \"This does not reflect the hard work\" lol ok.",
  },
  {
    id: 5,
    company: "Google",
    ticker: "GOOGL",
    emoji: "🔍",
    accentColor: "#4285f4",
    count: 12000,
    pct: 6,
    date: "2023-01-20",
    vibe: "nuclear",
    vibeLabel: "☢️ NUCLEAR",
    note: "\"We hired for a different economic reality.\" Sundar apologized. The 12,000 found out via locked badge.",
  },
  {
    id: 6,
    company: "Microsoft",
    ticker: "MSFT",
    emoji: "🪟",
    accentColor: "#00a4ef",
    count: 10000,
    pct: 5,
    date: "2023-01-18",
    vibe: "cope",
    vibeLabel: "💪 COPE",
    note: "Announced the same week as the $10B OpenAI investment. The irony of laying off humans to fund the machines.",
  },
  {
    id: 7,
    company: "SAP",
    ticker: "SAP",
    emoji: "🧩",
    accentColor: "#0faaff",
    count: 8000,
    pct: 8,
    date: "2024-01-23",
    vibe: "cope",
    vibeLabel: "💪 COPE",
    note: "\"AI transformation\". Classic 'we fired you so the robot can have your desk'. Pivoting to vibes.",
  },
  {
    id: 8,
    company: "Salesforce",
    ticker: "CRM",
    emoji: "☁️",
    accentColor: "#00a1e0",
    count: 8000,
    pct: 10,
    date: "2023-01-04",
    vibe: "cope",
    vibeLabel: "💪 COPE",
    note: "Benioff said he takes \"full responsibility\". Then kept his job, his jet, and his Hawaiian estate.",
  },
  {
    id: 9,
    company: "Twitter / X",
    ticker: "X",
    emoji: "✖️",
    accentColor: "#1da1f2",
    count: 6000,
    pct: 80,
    date: "2022-11-04",
    vibe: "cursed",
    vibeLabel: "🧿 CURSED",
    note: "80% of the company. In a weekend. Elon fired people, then begged some to come back. Musk behavior.",
  },
  {
    id: 10,
    company: "Cisco",
    ticker: "CSCO",
    emoji: "📡",
    accentColor: "#1ba0d7",
    count: 4000,
    pct: 5,
    date: "2024-02-14",
    vibe: "yikes",
    vibeLabel: "😬 YIKES",
    note: "Valentine's Day layoffs. Roses are red, violets are blue, your badge stopped working — we ❤️ you.",
  },
  {
    id: 11,
    company: "Goldman Sachs",
    ticker: "GS",
    emoji: "💰",
    accentColor: "#6ab04c",
    count: 3200,
    pct: 6,
    date: "2023-01-11",
    vibe: "yikes",
    vibeLabel: "😬 YIKES",
    note: "Must be rough watching your bonus vaporize from the Hamptons. Banks having \"a moment\".",
  },
  {
    id: 12,
    company: "PayPal",
    ticker: "PYPL",
    emoji: "💳",
    accentColor: "#003087",
    count: 2500,
    pct: 9,
    date: "2024-01-26",
    vibe: "yikes",
    vibeLabel: "😬 YIKES",
    note: "New CEO, same old \"difficult but necessary\" email template. At least the severance was sent via Venmo.",
  },
  {
    id: 13,
    company: "Spotify",
    ticker: "SPOT",
    emoji: "🎵",
    accentColor: "#1db954",
    count: 1500,
    pct: 17,
    date: "2023-12-04",
    vibe: "cursed",
    vibeLabel: "🧿 CURSED",
    note: "CEO blamed \"macroeconomic conditions\". The laid-off made a playlist: \"Songs for the Unemployment Line\".",
  },
  {
    id: 14,
    company: "Snap",
    ticker: "SNAP",
    emoji: "👻",
    accentColor: "#fffc00",
    count: 1300,
    pct: 20,
    date: "2023-08-29",
    vibe: "cursed",
    vibeLabel: "🧿 CURSED",
    note: "The ghost mascot becomes more literal every quarter. Stories disappear. So do employees.",
  },
  {
    id: 15,
    company: "Lyft",
    ticker: "LYFT",
    emoji: "🚗",
    accentColor: "#ff00bf",
    count: 1072,
    pct: 26,
    date: "2023-04-27",
    vibe: "nuclear",
    vibeLabel: "☢️ NUCLEAR",
    note: "New CEO's first ride was straight into HR. One in four employees. \"Smooth ride\" does not apply here.",
  },
];
